global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "telemetry-sample-1"
    scrape_interval: 5s
    static_configs:
    - targets: ["host.docker.internal:8080"]

  - job_name: "telemetry-sample-2"
    scrape_interval: 5s
    static_configs:
    - targets: ["host.docker.internal:9091"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]