apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-sample-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry-sample-python
  template:
    metadata:
      labels:
        app: telemetry-sample-python
    spec:
      containers:
      - name: telemetry-sample-python
        image: locmai/telemetry-sample:python-0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-sample-python
  labels:
    app: telemetry-sample-python
spec:
  ports:
  - port: 8080
    targetPort: 8080 # match with container port above
    name: http
  selector:
    app: telemetry-sample-python
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: telemetry-sample-python
  labels:
    app: telemetry-sample-python
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: telemetry-sample-python
  endpoints:
  - port: http # name of the port serve /metrics path

