apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-sample-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry-sample-python
      client: statsd
  template:
    metadata:
      labels:
        app: telemetry-sample-python
        client: statsd
    spec:
      containers:
      - name: telemetry-sample-python
        image: locmai/telemetry-sample:statsd-python-0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-sample-python
  labels:
    app: telemetry-sample-python
    client: statsd
spec:
  ports:
  - port: 8080
    targetPort: 8080 # match with container port above
    name: http
  selector:
    app: telemetry-sample-python